#lang racket
(printf "~a\n" 0)
(printf "~a\n" 1)
(define a 1)
(define b (+ a a))
(printf "~a\n" a)
(printf "~a\n" b)
(define (loopme)
    (set! a (+ a b))
    (set! b (+ a b))
    (printf "~a\n" a)
    (printf "~a\n" b)
    (if (< a 1000000) (loopme) (display ""))
)
(loopme)
